name: Kernel Builder Samsung-J4

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initialize environment
         run: |
            sudo apt-get Update
            sudo apt-get install -y build-essential kernel-package libncurses5-dev bzip2 git
            echo -e "\nCheck GCC ..."
            gcc
            echo -e "\nCheck MAKE ..."
            make

       - name: Clone kernel source and compiler
         run: |
            mkdir kernel
            cd kernel
            git clone https://github.com/synt4x93/android_kernel_samsung_universal7570 source
            git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 -b lineage-17.1 toolchain

       - name: Compile KERNEL
         run: |
            export cross_compile=/home/runner/work/Kernel-CI/Kernel-CI/kernel/toolchain/bin/aarch64-linux-android-
            export ARCH=arm64
            make exynos7570_j4lte-defconfig
            make -j18
