name: Building recovery

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Check specs
         run: |
            sudo apt install neofetch
            neofetch
